### ISSUE TITLE
embed的方法有问题

### ISSUE THREAD

**Issue by redpeer** [dong-zhang1/blind-watermark-based-on-DWT-SVD#1]
请问下embed里面的那个wm数组你取的是哪个呢？不然 wm[i,j]都是为空的呢

**Comment by zhangbanxian123** [comment]
wm是读取的要添加的水印的数组
wm = cv2.imread('./data/'+wmname,cv2.IMREAD_GRAYSCALE)
embed函数中使用的是这里的wm
